### ISSUE TITLE
Preface - Code examples. oreillymedia/title_title 404

### ISSUE THREAD

**Issue by submersibletoaster** [elastic/elasticsearch-definitive-guide#14]
http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/_using_code_examples.html

This is link
https://github.com/oreillymedia/title_title

I expect should point to a different title.

**Comment by danielmitterdorfer** [comment]
There is no erroneous link on this page anymore. Closing.

**Comment by parthasarathi204** [comment]
the link does not work

**Comment by danielmitterdorfer** [comment]
> the link does not work

@parthasarathi204 Can you please explain to me which link do you mean? As I said, there is no such link. The only "link" is a "mailto link" to permissions@oreilly.com and that one does work.
