### ISSUE TITLE
Field length norm calculation is wrong

### ISSUE THREAD

**Issue by laszbalo** [elastic/elasticsearch-definitive-guide#235]
In http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/scoring-theory.html#field-norm
the expression used to calculate field length norm is not correct. 

The Lucence API says that is calculated as follows:

**1 /  Math.sqrt(numTerms)**

http://lucene.apache.org/core/3_0_3/api/all/org/apache/lucene/search/DefaultSimilarity.html#lengthNorm(java.lang.String, int)

However when I tested, the above formula gave different result than ES.

Let's say, I have four document where the title field takes on four different different values, these are:
"java" -> numTerms = 1
"java developer" -> numTerms = 2
"java developer london" -> numTerms = 3
"java spring developer london" -> numTerms = 4

<table>
  <tr>
    <th>Math.sqrt(numTerms)</th>
    <th>1 / Math.sqrt(numTerms )</th>
    <th>Result returned by ES</th>
  </tr>
  <tr>
    <td>1</td>
    <td>1</td>
    <td>1</td>
  </tr>
  <tr>
    <td>1.41</td>
    <td>0.70</td>
    <td>0.62</td>
  </tr>
  <tr>
    <td>1.73</td>
    <td>0.57</td>
    <td>0.50</td>
  </tr>
  <tr>
    <td>2</td>
    <td>0.50</td>
    <td>0.50</td>
  </tr>
</table>

With thanks,
Laszlo

**Comment by tjvg91** [comment]
Sorry if I'm slow.

So what happens exactly if precision is lost?
