### ISSUE TITLE
The hyperlinks on available_buckets_and_metrics are all routed to fuzzy queries

### ISSUE THREAD

**Issue by NorthStar** [elastic/elasticsearch-definitive-guide#271]
[Webpage](http://www.elasticsearch.org/guide/en/elasticsearch/guide/current/_available_buckets_and_metrics.html)

[Code] (../blob/master/300_Aggregations/28_bucket_metric_list.asciidoc)

[The commit](https://github.com/elasticsearch/elasticsearch-definitive-guide/commit/0501e43ef09d037651a2ba1bd7ead1987c422c5d) that broke it.

skalapurakkel@oreilly.com (Can't tag)

**Comment by markwalkom** [comment]
@NorthStar this is no longer applicable so I'm going to close this. Sorry we were slow in getting back to you here :)

**Comment by NorthStar** [comment]
It's okay. I understand.
