### ISSUE TITLE
"View in Sense" links not working as expected

### ISSUE THREAD

**Issue by Zelfapp** [elastic/elasticsearch-definitive-guide#330]
For new users the documentation found at http://www.elastic.co/guide/en/elasticsearch/guide/master/_installing_elasticsearch.html is incomplete in regards to what to expect when clicking on "View in Sense" links in the definitive guide.

When I click "View in Sense" in Firefox or Chrome (Windows) I'm expecting to see the sample code and be able to run it against sample data to see the results documented in the guide. 

I created a youtube video (https://www.youtube.com/watch?v=4Ksb0t_9Ym0) to demonstrate the issue I'm finding when trying to click "View in Sense". When I click on "View in Sense" anywhere in the definitive guide, no json is being loaded, and the server field gets wiped out. Super confusing. When I click on the green run icon I get a cors settings error, presumably because there is no host in the server field now that I've clicked on "View in Sense", which wiped out my localhost server.

Is the server field in Sense supposed to be populated to an elasticsearch demo data host when I click on "View in Sense"? Was I supposed to download sample data referenced in the guide and add it to my localhost? Or is the data completely hypothetical and I can't run the sample code? This is fine, but for brand new users it should be spelled out in the "View in Sense" explanation.

On http://www.elastic.co/guide/en/elasticsearch/guide/master/_installing_elasticsearch.html it states, "Many of the code examples in the online version of this book include a View in Sense link. When clicked, it will open up a working example of the code in the Sense console. You do not have to install Marvel, but it will make this book much more interactive by allowing you to experiment with the code samples on your local Elasticsearch cluster." So it appears the sample data should be local?

My guess would be my issue is most likely due to running on crappy windows or I missed a critical setup step for either Sense, Marvel, elasticsearch.yml, or the definitive guide. Would love to hear why this isn't working and what step, if any, I skipped. For brand new learners to ES this kind of stuff should be spelled out a litter more in the Getting Started section in my opinion. Thank you.

**Comment by clintongormley** [comment]
Hi @Zelfapp 

It's a problem with the new website - it is missing  CORS header.  Our web team are in the process of getting this fixed. Sorry for the trouble

**Comment by Zelfapp** [comment]
Ah, I see. I thought that might be. A lot of links out there are not redirecting to the new domain correctly either. Good to know. So do I have it right then, once cors header issue is resolved will the server field be populated to run the working code examples against actual sample data for the twitter tutorial in getting started?

**Comment by clintongormley** [comment]
@Zelfapp you need to run elasticsearch locally, you won't be communicating with a remote cluster. the examples are completely separate from the twitter app, but most of them are self contained
