### ISSUE TITLE
Does match_phrase actually use spans internally?

### ISSUE THREAD

**Issue by mattweber** [elastic/elasticsearch-definitive-guide#335]
In the phrase matching section there is a tip [1] that says match_phrase uses spans internally.  

"""
Internally, the match_phrase query uses the low-level span query family to do position-aware matching....
"""

Is this true?  I can't seem to find this in ES or Lucene sources.

[1] http://www.elastic.co/guide/en/elasticsearch/guide/current/phrase-matching.html#_what_is_a_phrase

**Comment by polyfractal** [comment]
Eep, no, I don't think they do? Will investigate, but I'm pretty sure they just just compare position's and don't dive into the hellish underworld that is the span family :)

(also, sorry for delay on this :) )

**Comment by mattweber** [comment]
Haha no problem, I can't even remember what had triggered me to look at this.  I think I was interested in exposing `in_order` if they did actually use spans.  At any rate, no biggie.  Thanks!
