### ISSUE TITLE
Update max heap size recommendations to 30.5GB

### ISSUE THREAD

**Issue by markwalkom** [elastic/elasticsearch-definitive-guide#370]
And not 32GB as per advice from Oracle.

**Comment by malpani** [comment]
@markwalkom Are there any links from oracle which talk about why 30.5 GB as against 32 GB which is what I see on their site [1]
[1] http://docs.oracle.com/javase/7/docs/technotes/guides/vm/performance-enhancements-7.html#compressedOop

**Comment by mfelsche** [comment]
@markwalkom this page (and all others i've found) https://wiki.openjdk.java.net/display/HotSpot/CompressedOops also states that the upper limit is 32 GB.

Is it due to heap alignment? Any insights?

**Comment by mfelsche** [comment]
@markwalkom i was able to verify that compressed oops are enabled up to 32 GB of heap, not 30.5 GB in the hotspot vm using:

```
$ java -XX:+UnlockDiagnosticVMOptions -XX:+PrintCompressedOopsMode -Xmx31999m -XX:+UseCompressedOops -version

Protected page at the reserved heap base: 0x0000000118200000 / 2097152 bytes

heap address: 0x0000000118400000, size: 32000 MB, Compressed Oops with base: 0x00000001183ff000

Narrow klass base: 0x000000093151d000, Narrow klass shift: 0
Compressed class space size: 1073741824 Address: 0x000000093151d000 Req Addr: 0x00000008e8400000
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

```
$ java -XX:+UnlockDiagnosticVMOptions -XX:+PrintCompressedOopsMode -Xmx32g -XX:+UseCompressedOops -version
Java HotSpot(TM) 64-Bit Server VM warning: Max heap size too large for Compressed Oops
java version "1.8.0_60"
Java(TM) SE Runtime Environment (build 1.8.0_60-b27)
Java HotSpot(TM) 64-Bit Server VM (build 25.60-b23, mixed mode)
```

So what exactly is the reasoning behind this change/advice?

**Comment by markwalkom** [comment]
Here's a few links;
 * http://docs.oracle.com/javase/7/docs/technotes/guides/vm/performance-enhancements-7.html
 * https://blogs.oracle.com/poonam/entry/running_on_a_64bit_platform
