### ISSUE TITLE
Testing Analyzers not working

### ISSUE THREAD

**Issue by Eschon** [elastic/elasticsearch-definitive-guide#374]
When I try to run the code at [Testing Analyzers](https://www.elastic.co/guide/en/elasticsearch/guide/current/analysis-intro.html#analyze-api) in Sense it does Not work.

![screen shot 2015-06-18 at 12 39 20](https://cloud.githubusercontent.com/assets/11647830/8229447/1e6b9c12-15b7-11e5-810d-52adb417630b.png)

When I hover the x-Symbol right to line 2 it says: 
```
Expected one of GET/POST/PUT/DELTETE/HEAD
Syntax error
```

**Comment by cwurm** [comment]
When you click the "View in Sense" button it will show the query as it would work in Sense: GET /_analyze?analyzer=standard&text=Text to analyze

The problem is that Sense does not accept text bodies. #128
