### ISSUE TITLE
PORT missing in URI

### ISSUE THREAD

**Issue by iiordanov** [elastic/elasticsearch-definitive-guide#383]
Hello!

I am reading your excellent guide, and I noticed that in 15_API.asciidoc, PORT is missing from the example HTTP request:

`curl -X<VERB> '<PROTOCOL>://<HOST>/<PATH>?<QUERY_STRING>' -d '<BODY>'`

Should be:

`curl -X<VERB> '<PROTOCOL>://<HOST>:<PORT>/<PATH>?<QUERY_STRING>' -d '<BODY>'`

Cheers and many thanks!
iordan iordanov

**Comment by thiagolocatelli** [comment]
PATH is missing in the explanation table underneath

**Comment by polyfractal** [comment]
Fixed via #320 :)
