### ISSUE TITLE
Incorrect result in example

### ISSUE THREAD

**Issue by jayartz** [elastic/elasticsearch-definitive-guide#386]
On the page: https://www.elastic.co/guide/en/elasticsearch/guide/current/_controlling_analysis.html

There is an example comparing the title and the english_title. They both show the result to be the same (foxes) though in the footnotes, it shows the expected results to be different (foxes vs fox).

Thanks for a great book!

**Comment by danielmitterdorfer** [comment]
The output in the referenced example is correct now. Hence closing.
