### ISSUE TITLE
Rolling restarts doesn't incorporate synced flush

### ISSUE THREAD

**Issue by GlenRSmith** [elastic/elasticsearch-definitive-guide#408]
Should 520_Post_Deployment/40_rolling_restart.asciidoc follow https://www.elastic.co/guide/en/elasticsearch/reference/current/setup-upgrade.html#rolling-upgrades?

**Comment by polyfractal** [comment]
It should! Adding to 2.x tag so I don't forget this in the updates.

**Comment by ppf2** [comment]
+1 have users getting confused due to the differences :)

**Comment by GlenRSmith** [comment]
This is still a problem.
