### ISSUE TITLE
Translog says default of 200MB instead of 512MB

### ISSUE THREAD

**Issue by damianpfister** [elastic/elasticsearch-definitive-guide#467]
The following statement appears to conflict with what is on https://www.elastic.co/guide/en/elasticsearch/reference/current/index-modules-translog.html#_flush_settings.

```
Finally, you can increase `index.translog.flush_threshold_size` from the default
200 MB to something larger, such as 1 GB
```

**Comment by polyfractal** [comment]
Fixed in d79aa55a37f9795cd2b9f28b1cdda8b1ea069405.

Thanks!
