### ISSUE TITLE
How to tell if Elasticsearch-2.2.0 is working? 

### ISSUE THREAD

**Issue by FernRaff** [elastic/elasticsearch-definitive-guide#486]
Im new with both Linux (centOS) & ELK stack, I think I configered ElasticSearch correctly, though im not sure. So my question is:

How to tell if Elasticsearch-2.2.0 is working properly? 

A follow up question would be what should i install next? Kibana or Logstash. Or does not matter?

**Comment by dadoonet** [comment]
Please ask your questions on discuss.elastic.co. We will be happy to help there!

To check if elasticsearch is running just open http://localhost:9200
