### ISSUE TITLE
the  explain of search parameter `timeout` need refresh?

### ISSUE THREAD

**Issue by chenryn** [elastic/elasticsearch-definitive-guide#547]
The `warning` in <https://github.com/elastic/elasticsearch-definitive-guide/blob/master/050_Search/05_Empty_search.asciidoc> said that `timeout` don't halt the exec of query.
Is is true in Elasticsearch 2.x?

**Comment by polyfractal** [comment]
It is.  The timeout still doesn't "cancel" the search on the various shards, just on the coordinating node.  Perhaps in the future that won't be the case, since we now have a task management API, but for now it's still true. :(
