### ISSUE TITLE
Configuration option change for Logstash netflow plugin.

### ISSUE THREAD

**Issue by A-Hall** [elastic/elasticsearch-definitive-guide#599]
In reference to: https://www.elastic.co/guide/en/logstash/current/plugins-codecs-netflow.html

Between the netflow codec versions 2.0.5 and 2.1.0 the syntax for the configuration option `definitions` changed to `netflow_definitions`.  I cracked open the older versions of the code on github and verified the syntax per version.  Below I made a table so you can easily update the corresponding pages on the guide.  Logstash v2.3.2 is correct, all later version pages should be updated.

```
Logstash version - codec version - configuration option syntax
Logstash 2.4     - codec 2.1.1   - netflow_definitions
Logstash 2.3.4   - codec 2.1.0   - netflow_definitions
Logstash 2.3.3   - codec 2.1.0   - netflow_definitions
Logstash 2.3.2   - codec 2.0.5   - definitions
```

**Comment by danielmitterdorfer** [comment]
I think this is unrelated to the Definitive Guide which is exclusively about Elasticsearch. Hence closing.
