### ISSUE TITLE
"View in console" links not working as expected in Elasticsearch Reference[5.0]

### ISSUE THREAD

**Issue by charany1** [elastic/elasticsearch-definitive-guide#639]
Problem : Commands are not loaded into Console when Console is already open , it simply results in switching to Console tab 

Steps to reproduce : 
1. Open https://www.elastic.co/guide/en/elasticsearch/reference/current/_create_an_index.html 
2. Click on `VIEW IN CONSOLE` => Should open a new tab
3. Go to next page : https://www.elastic.co/guide/en/elasticsearch/reference/current/_index_and_query_a_document.html

4. Click on `VIEW IN CONSOLE` => doesn't copies the commands into already opened Console tab , simply switches to Console tab 

However , when I do _Open Link In New Tab_  after Right Click on `VIEW IN CONSOLE` it loads the commands into a fresh  Console Tab?
Is it expected behavior ?

**Comment by clintongormley** [comment]
This issue was moved to elastic/kibana#9396
