### ISSUE TITLE
Logstash 5.0 basic auth unclear documentation.

### ISSUE THREAD

**Issue by A-Hall** [elastic/elasticsearch-definitive-guide#641]
https://www.elastic.co/guide/en/x-pack/5.0/logstash.html#ls-http-auth-basic

Step 1 says to make sure that the role has the "manage_index_templates" privilege.  The example shows both the "manage_index_templates" and the "monitor" cluster privilege.   It would be more clear if the monitor cluster was mentioned in the text in addition to the sample.

**Comment by danielmitterdorfer** [comment]
I think this is unrelated to the Definitive Guide which is exclusively about Elasticsearch. Hence closing.
