### ISSUE TITLE
Aggregation Test-Drive example error

### ISSUE THREAD

**Issue by edgarshurtado** [elastic/elasticsearch-definitive-guide#655]
I'm running ElasticSearch 5.1.2 and by following the steps in the book for my first aggregation, the following error is displayed:

> Fielddata is disabled on text fields by default. Set fielddata=true on [color] in order to load fielddata in memory by uninverting the inverted index. Note that this can however use significant memory.

After some research, for being able to aggregate by this field I had to execute: 

```
POST cars/transaction/_search

{
    "size" : 0,
    "aggs" : { 
        "popular_colors" : { 
            "terms" : { 
              "field" : "color.keyword"
            }
        }
    }
}
```
> I've used *POST* because my application for testing APIs (the *Advanced REST Client* Chrome extension)  doesn't allow me to add a request body on *GET* (not sure if the error could be because of this).
 In my opinion, It will be more begginer friendly if this would be explained. I had to spend a couple of hours reading about mapping, fielddata and finally keywords to get the aggregation running.

I can add this modifications in a pull request if you want.

**Comment by danielmitterdorfer** [comment]
Thanks for the report! It's now closed by #631.
